[profile.default]
optimizer = true
optimizer_runs = 200
via_ir = true
auto_detect_remappings = false
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/v4-core/lib/solmate/src/"
]

[rpc_endpoints]
# mainnet = "https://eth.llamarpc.com"