[profile.default]
# source folders
src = "src"
out = "out"
libs = ["lib"]

# compiler
solc_version = "0.8.24"   # matches v4-core at time of writing
optimizer = true
optimizer_runs = 10000
via_ir = true

# Cancun features (e.g. transient storage)
evm_version = "cancun"

# dependency resolution
auto_detect_remappings = false
remappings = [
    "@uniswap/v4-core/src/=lib/v4-core/src/",
    "@uniswap/v4-core/contracts/=lib/v4-core/src/",
    "@uniswap/v4-periphery/src/=lib/v4-periphery/src/",
    "@uniswap/v4-periphery/contracts/=lib/v4-periphery/src/",

    # --- other libs ---
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/v4-core/lib/solmate/src/"
]